name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm test
      - id: generate
        uses: ./
        with:
          top-directory: action-generate-tarball
          exclude: |
            ^\.git/
            ^node_modules/
      - run: |
          tar -tzf "${{ steps.generate.outputs.tarball }}" | grep '^action-generate-tarball/README.md$'
          ! tar -tzf "${{ steps.generate.outputs.tarball }}" | grep '^action-generate-tarball/.git/'
